export const CHECK_INS = [
  "what tiny thing made today feel a little softer?",
  "what was the best five seconds of your day?",
  "name one tiny thing your brain almost skipped over that was actually kinda nice.",
  "what felt unexpectedly cozy today?",
  "what was one little moment you wish you had noticed for two seconds longer?",
  "what sound did you actually enjoy today?",
  "what made you smile before you had time to overthink it?",
  "what was one tiny inconvenience that somehow turned out okay?",
  "what did you see today that was weirdly pretty?",
  "what small comfort did past-you accidentally leave for current-you?",
  "what tasted extra good today for no dramatic reason?",
  "what was one moment today where you felt fully here instead of on autopilot?",
  "what tiny thing made your space feel like yours today?",
  "what was the nicest texture you touched today? yes this is important science.",
  "what ordinary thing felt a little special today?",
  "what was one moment today that felt like a tiny commercial break from life?",
  "what did you laugh at today, even if it was incredibly stupid?",
  "what tiny thing are you glad happened exactly the way it did?",
  "what was one little 'oh wait, this is nice' moment today?",
  "what did the sky look like the last time you actually looked at it?",
  "what tiny detail from today deserves to not disappear into the void?",
  "what was one small thing that made being a person less annoying today?",
  "what smell made your brain go 'waitttt okay'?",
  "what part of today would you put in a tiny snow globe if you could?",
  "what did you do slowly today without meaning to?",
  "what was one tiny moment that felt safe?",
  "what background noise made today feel a little more alive?",
  "what was one tiny thing you got to enjoy with absolutely no productive purpose?",
  "what did you notice today that you usually ignore?",
  "what was one small moment where your shoulders dropped a little?",
  "what tiny thing made you feel cared for today, even accidentally?",
  "what was the coziest ten seconds of your day?",
  "what did you see today that looked like it belonged in a movie scene?",
  "what tiny thing would you miss if today got completely erased?",
  "what was one nice thing your body got to experience today?",
  "what tiny routine felt comforting instead of boring today?",
  "what moment today made you think 'okayyy life, you ate that one'?",
  "what was one harmless little thing you were excited about today?",
  "what tiny bit of peace showed up without being invited?",
  "what was one thing you touched today that felt oddly satisfying?",
  "what tiny part of your day deserves a replay?",
  "what was something completely normal that made you happy anyway?",
  "what did you hear today that made the world feel less quiet?",
  "what tiny moment felt like being tucked in by the universe a lil bit?",
  "what was one small thing you did purely because you wanted to?",
  "what tiny thing made today feel different from yesterday?",
  "what was one little moment you didn't need to take a picture of to enjoy?",
  "what did you notice outside today, even if it was just for a second?",
  "what tiny thing made your brain feel less loud?",
  "what was one unexpectedly pleasant part of your usual routine?",
  "what tiny thing made you feel more like yourself today?",
  "what was one moment today where nothing needed fixing?",
  "what little thing felt luxurious even though it absolutely was not?",
  "what was one tiny thing you were lucky enough to catch at the right moment?",
  "what made you pause today, in a good way?",
  "what tiny detail made a boring moment less boring?",
  "what was one moment where you forgot to check the time?",
  "what small thing did you enjoy that nobody else needed to know about?",
  "what was one tiny moment that made the day feel less copy-paste?",
  "what did you eat or drink today that deserved a tiny round of applause?",
  "what tiny thing felt familiar in the best way?",
  "what was one little thing that made home feel like home today?",
  "what did you catch yourself genuinely looking forward to?",
  "what tiny thing made you laugh at yourself today?",
  "what was one peaceful moment you almost rushed through?",
  "what tiny thing made you feel warm, literally or emotionally?",
  "what was one thing today that was nicer than it had to be?",
  "what tiny thing made you think 'wait, I kinda love this'?",
  "what was one moment where your brain finally stopped narrating everything?",
  "what little detail from today would make a cute diary entry?",
  "what tiny thing felt like a reward even though you didn't have to earn it?",
  "what was one tiny thing that made you feel connected to another person?",
  "what did you do today that felt delightfully unnecessary?",
  "what tiny thing made the room feel better when you noticed it?",
  "what was one moment where you let yourself just exist?",
  "what small part of today felt sweeter than expected?",
  "what tiny thing would you tell tomorrow-you not to rush past?",
  "what was one tiny thing you noticed with your senses instead of your thoughts?",
  "what little moment made today feel worth remembering for no big reason?",
  "what tiny joy snuck into your day while you weren't paying attention?",
  "what was one little thing that made you feel less like a floating brain with bills?",
  "what tiny thing did you enjoy before your brain could label it productive or unproductive?",
  "what was one ordinary moment you would weirdly miss someday?",
  "what tiny thing made you feel a little more awake to your own life today?",
  "what was one small thing that made the day gentler?",
  "what tiny thing happened today that you hope happens again?",
  "what was one little moment where you thought 'this is enough for right now'?",
  "what tiny detail did today hide in plain sight for you?",
  "what was one moment you actually enjoyed without needing it to become anything else?",
  "what tiny thing made you glad you were paying attention?",
  "what did today give you that wasn't an accomplishment, just a nice little thing?",
  "what tiny part of today felt like yours and nobody else's?",
  "what was one stupidly small thing that improved your mood?",
  "what tiny thing would get a five-star review from you today?",
  "what was one little moment that made being alive feel kinda cute?",
  "what tiny thing did you notice once you stopped rushing for a second?",
  "what was one small moment today that didn't ask anything from you?",
  "what tiny comfort are you sitting near right now?",
  "what was one moment from today you want to mentally put a little heart around?"
];
