export const HAPPY_JOKES = [
  ["What do you call cheese that isn’t yours?", "Nacho cheese."],
  ["Why did the math book look so stressed?", "Because it had too many problems."],
  ["What do you call a bear with no teeth?", "A gummy bear."],
  ["Why don’t eggs tell jokes?", "They’d crack each other up."],
  ["What did one wall say to the other wall?", "I’ll meet you at the corner."],
  ["Why did the scarecrow win an award?", "He was outstanding in his field."],
  ["What do you call a sleeping bull?", "A bulldozer."],
  ["Why was the broom late?", "It over-swept."],
  ["What kind of shoes do ninjas wear?", "Sneakers."],
  ["What do clouds wear under their shorts?", "Thunderwear."],
  ["Why did the cookie go to the doctor?", "It was feeling crumby."],
  ["What do you call a fake noodle?", "An impasta."],
  ["Why couldn’t the bicycle stand up by itself?", "It was two-tired."],
  ["Why did the coffee file a police report?", "It got mugged."],
  ["What did the ocean say to the beach?", "Nothing. It just waved."],
  ["Why did the computer go to therapy?", "It had too many unresolved issues."],
  ["What do you call a fish wearing a bowtie?", "Sofishticated."],
  ["Why was six afraid of seven?", "Because seven eight nine."],
  ["What do you call a pile of cats?", "A meowtain."],
  ["Why did the banana go to the doctor?", "It wasn’t peeling well."],
  ["What do you call an alligator in a vest?", "An investigator."],
  ["Why did the tomato blush?", "It saw the salad dressing."],
  ["What did zero say to eight?", "Nice belt."],
  ["Why are elevator jokes so good?", "They work on many levels."],
  ["What do you call a cow with no legs?", "Ground beef."],
  ["Why did the mushroom get invited to every party?", "Because he was a fungi."],
  ["What do you call a dinosaur with an extensive vocabulary?", "A thesaurus."],
  ["Why did the golfer bring two pairs of pants?", "In case he got a hole in one."],
  ["Why was the calendar nervous?", "Its days were numbered."],
  ["What do you call a boomerang that won’t come back?", "A stick."],
  ["Why did the music teacher need a ladder?", "To reach the high notes."],
  ["What do you call a very small valentine?", "A valen-tiny."],
  ["Why did the phone wear glasses?", "It lost its contacts."],
  ["What did the left eye say to the right eye?", "Between us, something smells."],
  ["Why did the picture go to jail?", "Because it was framed."],
];

export const DAY_QUESTS = {
  Sunday: [
    ["Drink something you actually like.", "Give yourself one slow little pocket of time.", "Reset one tiny thing that would make tomorrow nicer.", "Do something cozy on purpose."],
    ["Hydrate at some point. Revolutionary, I know.", "Put one thing back where Future You can find it.", "Take the long version of one small comfort.", "Be gentle with your Sunday brain."],
    ["Find ten minutes with no urgency attached.", "Make your space a tiny bit softer.", "Eat something before you become mysteriously furious.", "Let today be enough."],
    ["Notice what your body is asking for.", "Do one tiny reset, not an entire life overhaul.", "Pick one thing you’re looking forward to this week.", "Get cozy before you technically need to."],
  ],
  Monday: [
    ["Fuel yourself with something other than caffeine, if you can.", "Drink some water. Future You will appreciate it.", "Stretch your legs every now and then.", "Cross one tiny thing off your to-do list.", "Don’t forget to take care of yourself, too."],
    ["Do not emotionally become your inbox.", "Eat something with actual substance in it.", "Give your eyeballs a break from a screen once or twice.", "Choose one tiny thing that would make today easier.", "That is enough Mondaying for one Monday."],
    ["Start slower than your brain thinks you’re allowed to.", "Have some water before you become a raisin.", "Do the easiest useful thing first.", "Find one harmless little thing to look forward to.", "Clock out mentally when you clock out physically."],
    ["Unclench something. Jaw. Shoulders. Entire soul.", "Put food in the human.", "Handle one little thing you’ve been side-eyeing.", "Take one unnecessary cozy break.", "Monday does not get to have your whole personality."],
  ],
  Tuesday: [
    ["Drink water before your body submits a formal complaint.", "Do one thing without rushing it.", "Step away from your screen for a minute.", "Give yourself one tiny treat just because.", "Keep Tuesday mildly supervised."],
    ["Eat before the random 3 PM personality change.", "Fix one tiny annoyance in your immediate area.", "Notice one thing outside.", "Do something in the easiest acceptable way.", "You do not need to optimize Tuesday."],
    ["Move your body in literally any non-dramatic way.", "Have a beverage you enjoy.", "Finish one tiny loose end if it feels good.", "Let one thing wait without making it a moral issue.", "Stay a person, not a productivity app."],
    ["Check whether you’re hungry before assuming life is terrible.", "Look away from the glowing rectangle.", "Make one boring thing slightly more pleasant.", "Give yourself something to look forward to tonight.", "Proceed with suspicious amounts of coziness."],
  ],
  Wednesday: [
    ["Hydrate. We have made it too far to turn into dust now.", "Do one tiny favor for tonight-you.", "Take a real break instead of changing tabs.", "Find something mildly delightful.", "Halfway counts."],
    ["Eat a snack before you begin beefing with existence.", "Stretch whatever has been folded into a shrimp shape.", "Do one small thing that makes your space nicer.", "Let one task be good enough.", "Wednesday is not the final boss."],
    ["Take a second to notice where the day actually is.", "Get some water into the organism.", "Put on something that makes the next hour nicer.", "Answer one thing, ignore one thing, survive one thing.", "Be nice to the little guy in your brain."],
    ["Give yourself one moment that is not for work.", "Eat something before your thoughts get theatrical.", "Move rooms or step outside for a tiny reset.", "Pick one thing that can wait until tomorrow.", "Midweek maintenance complete-ish."],
  ],
  Thursday: [
    ["Have some water. Almost-weekend you needs it.", "Do one thing Future You would call considerate.", "Take one break before you desperately need one.", "Find one tiny thing to enjoy tonight.", "Thursday is basically Friday’s loading screen."],
    ["Feed yourself like you are responsible for a small creature. Because technically.", "Move around enough to remind your legs they exist.", "Finish one easy thing if it’ll make your brain quieter.", "Put one nice thing in your evening.", "Do not spend Friday’s energy today."],
    ["Hydrate before you get dramatic.", "Make one annoying thing less annoying.", "Let yourself be done with something at good enough.", "Notice one thing that went right by accident.", "Save some whimsy for tomorrow."],
    ["Take a tiny pause before the next thing.", "Eat something with structural integrity.", "Clear one microscopic patch of chaos.", "Pick your evening comfort in advance.", "Nearly there, lil dude."],
  ],
  Friday: [
    ["Hydrate before the weekend claims you.", "Wrap up one tiny loose end if you feel like it.", "Do something you actually enjoy today.", "Acquire a snack of reasonable emotional importance.", "You made it."],
    ["Eat the snack.", "Do not create three new Friday emergencies for yourself.", "Take one celebratory little break.", "Pick something fun for later.", "Weekend loading..."],
    ["Drink water so Saturday-you doesn’t wake up confused.", "Finish what genuinely needs finishing.", "Leave the fake emergencies where they belong.", "Put one joyful thing on the agenda.", "Release yourself from the week."],
    ["Keep today cute and moderately functional.", "Have a beverage with a little personality.", "Do the minimum amount of Friday heroics.", "Celebrate one tiny thing that went okay this week.", "Log off spiritually when appropriate."],
  ],
  Saturday: [
    ["Hydrate at some mysterious point today.", "Touch grass, a window, or at least some fresh air.", "Do what makes you happy for no productive reason.", "Treat yourself to one tiny nice thing.", "Protect the Saturday vibes."],
    ["Move at weekend speed.", "Eat something you actually wanted.", "Do one thing solely because it sounds fun.", "Ignore one chore until later with confidence.", "Be unavailable to unnecessary urgency."],
    ["Have water eventually. No rush, your majesty.", "Leave the house or dramatically choose not to.", "Make something, play something, watch something, rot responsibly.", "Notice one tiny nice thing while it’s happening.", "Saturday has no performance review."],
    ["Do not accidentally turn your day off into unpaid labor.", "Find a snack.", "Get a little daylight on your person.", "Spend some time doing absolutely nothing useful.", "That is literally the quest."],
  ],
};

export const AS_ALWAYS = [
  "stay cozy",
  "stay weird",
  "stay funny",
  "and don’t forget to look both ways before crossing the street.",
];
